crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/',  include('users.urls', namespace="users")),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('categories/',  include('categories.urls', namespace="categories")),
    path('sources/',  include('sources.urls', namespace="sources")),
]

leads/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import LeadUpdateView, LeadView, lead_delete

app_name = 'users'

urlpatterns =[
    path('', login_required(LeadView.as_view()), name='lead-index'),
    path('<int:pk>/update/', login_required(LeadUpdateView.as_view()), name='lead-update'),
    path('<int:pk>/delete/', login_required(lead_delete), name='lead-delete'),

]

leads/models.py
from django.db import models
from users.models import User
from sources.models import Source
from categories.models import Category

class Lead(models.Model):
    
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=30, unique=True)
    email = models.CharField(max_length=30)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1500, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default='NEW')
    task = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, default='misen', on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

leads/forms.py
from .models import Lead, User, Category
from django import forms
from django.forms import Textarea
from flatpickr import DateTimePickerInput


class LeadModelForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields = (
        'name',
        'phone',
        'email',
        'source',
        'category',
        'task',
        'user',
        'comment',
    )

    widgets = {
        'comment': Textarea(attrs={'cols': 20, 'rows': 4}),
        'task': DateTimePickerInput(attrs={'placeholder':'Select Date/Time.'}),
    }

class LeadForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields = (
        'name',
        'phone',
        'email',
        'source',
        'user',
        'task',
    )

    widgets = {
        'task': DateTimePickerInput(attrs={'placeholder':'Select Date/Time.'}),
    }

leads/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from .models import Lead
from .forms import LeadForm, LeadModelForm
from django.core.exceptions import PermissionDenied


class LeadView(generic.CreateView):
    model = Lead
    template_name = "leads/lead_index.html"
    form_class = LeadModelForm

    def get_context_data(self, **kwargs):
        kwargs['leads'] = Lead.objects.order_by('-updated_at')
        return super(LeadView, self).get_context_data(**kwargs)
    def get_success_url(self):
       return reverse("leads:lead-index")


class LeadUpdateView(generic.UpdateView):
   model = Lead
   template_name = "leads/lead_update.html"
   form_class = LeadModelForm
    
   def get_success_url(self):
     return reverse("leads:lead-index")

def lead_delete(request, pk):
    lead = Lead.objects.get(id=pk)
    if request.user.is_superuser:
     lead.delete()
    else:
        raise PermissionDenied("Access forbidden 403. Are you root?")
    return redirect("/leads")

leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
{{form.media}}
<title>
    {% block title %}
      update {{lead.name}}
    {% endblock title %}
  </title>
<div class="container">
  <div class="well">
  <div class="row justify-content-center grid">
    <div class="col-lg-10 col-md-10 col-sm-10">
      <div class="card">
        <div class="card-header text-muted text-center">
          <h3 class="card-title">Create <b class="text-info">Lead</b> </h3>
        </div>
        <div class="card-body">
          <div class="jumbotron">
        <form action="" method="post">
          <div class="row">
          {% csrf_token %}
          <div class="form-group col-sm-4 col-md-6">
            {{ form.name.label_tag }}
            {% render_field form.name class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.category.label_tag }}
            {% render_field form.category class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.phone.label_tag }}
            {% render_field form.phone class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.source.label_tag }}
            {% render_field form.source class="form-control" %}
          </div>
          <div class="form-group col-sm-4 col-md-6">
            {{ form.email.label_tag }}
            {% render_field form.email class="form-control" %}
          </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.task.label_tag }}
              {% render_field form.task class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.user.label_tag }}
              {% render_field form.user class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-6">
              {{ form.comment.label_tag }}
              {% render_field form.comment class="form-control" %}
            </div>
          </div>
          </div>
        </div>
          <div class="card-footer text-muted text-center">
            <button type="submit" class="btn btn-success btn-block"><span class="fa fa-hdd" aria-hidden="true"></span> Create</button>
          </form>
          <h1 style="margin-top: 10px;"><a href="/leads"class="btn btn-danger btn-block"><span class="fa fa-undo" aria-hidden="true"></span> Back</a></h1>
          </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

leads/templates/leads/lead_index.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  leads
{% endblock title %}

{% block content %}
{{form.media}}


<div class="spoon">
  <div class="host">
    <h1 class="header">Welcome</h1>
    <h3>This is the personal workspace for <code>{{request.user.username}}</code>.</h3>
  </div>
  <div class="peer">
    <h2>Quickly create a new lead.</h2>
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.name class="form-control" placeholder="Name" style="border-radius: 20px;" %}
        {% render_field form.phone class="form-control" placeholder="Phone" style="border-radius: 20px;" %}
        {% render_field form.category class="form-control" placeholder="Category" style="border-radius: 20px;" %}

      </div>
      <div class="form-group">
        {% render_field form.email class="form-control" placeholder="Email" style="border-radius: 20px;" %}
        {% render_field form.source class="form-control" placeholder="Source" style="border-radius: 20px;" %}
        {% render_field form.user class="form-control" placeholder="User" style="border-radius: 20px;" %}

      </div>
      <button type="submit" class="btn btn-dark col-12">Create</button>
    </form>
  </div>
</div>
<div class="content">
  <table id="misen" class="table table-bordered table-hover nowrap table-sm" cellspacing="0" style="width:100%">
    {% csrf_token %}
	<thead class="thead-dark">
		<tr>
			<th class="text-center">#</th>
            {% if request.user.is_staff %}
            <th class="text-center"><input type="checkbox" name="" id="site_select_all"></th>
            {% endif %}
			<th class="text-center">Name</th>
			<th class="text-center">Phone</th>
			<th class="text-center">Data Creation</th>
			<th class="text-center">Source</th>
			<th class="text-center">Category</th>
            {% if request.user.is_staff %}
            <th class="text-center">User</th>
			<th class="text-center">Action</th>
            {% endif %}
		</tr>
	</thead>
	<tbody>
		{% for lead in leads %}
		<tr id="{{lead.id}}">
			<td class="text-center">{{lead.id}}</td>
            {% if request.user.is_staff %}
            <td class="text-center"><input type="checkbox" name="sel" id="delete_lead" value="{{lead.id}}"></td>
            {% endif %}
			<td class="text-center"><a href="{% url 'leads:lead-update' lead.pk %}">{{lead.name}}</a></td>
			<td class="text-center">{{lead.phone}}</td>
			<td class="text-center">{{lead.created_at|date:'Y-m-d'}}</td>
			<td class="text-center">{{lead.source}}</td>
			<td class="text-center">{{lead.category}}</td>
            {% if request.user.is_staff %}
            <td class="text-center">{{lead.user}}</td>
			<td class="text-center">
				<a href="{% url 'leads:lead-update' lead.pk %}"><i class="fas fa-edit text-primary"></i></a>
				<a href="{% url 'leads:lead-delete' lead.pk %}" onclick="return confirm('Are you sure to delete this Lead?');"><i class="fas fa-trash-alt text-danger"></i></a>
			</td>
            {% endif %}
		</tr>
		{% endfor %}
	</tbody>
</table>
</div>
<div class="mikrotik">
    
</div>
<script>
  function get_Selected_id() {
        var searchIDs = $("input[name=sel]:checked").map(function(){
            return $(this).val();
        }).get();
        return searchIDs;
    }

    $(document).ready(function() {
        var table = $('#misen').DataTable({
            "paging": true,
            "aLengthMenu": [[10, 25, 50, 100,], [10, 25, 50, 100,]],
            "iDisplayLength": 50,
            "searching": false,
            "responsive": true,
            "ordering":true,
            "order": []
        });
        // Handle click on "Select all" control
        $('#site_select_all').on('click', function(){
            // Check/uncheck all checkboxes in the table
            var rows = table.rows({ 'search': 'applied' }).nodes();
            $('input[type="checkbox"]', rows).prop('checked', this.checked);
        });

    $("#delete_all").click(function(event){
            event.preventDefault();
            if (confirm("Are you sure to Delete Selected?")) {
                var id = get_Selected_id();
                var csrf = $('input[name=csrfmiddlewaretoken').val();
                if (id!='') {
                    /*$('#delete_leads_ids').eq(0).val(leads_ids);
                    $('#delete_multiple_form').submit();*/
                    $.ajax({
                        url: "{%url 'leads:lead-index' %}",
                        method: "POST",
                        data: {
                            id,
                            csrfmiddlewaretoken:csrf,
                        },
                        success:function(response){
                            for(var i=0; i<id.length; i++){
                                $('tr#'+id[i]+'').css('background-color', '#ccc');
                                $('tr#'+id[i]+'').fadeOut('slow');
                            }
                            window.location.href = ".";
                        }
                    })

                } else {
                    return confirm("No leads selected");
                }
            }
            return false;
        });

       /* $("#delete_all").click(function(event){
            event.preventDefault();
            if (confirm("Are you sure to Delete Selected?")) {
                var leads_ids=get_Selected_id();
                if (leads_ids!='') {
                    $('#delete_leads_ids').eq(0).val(leads_ids);
                    $('#delete_multiple_form').submit();
                } else {
                    return confirm("No leads selected");
                }
            }
            return false;
        });
        $("#delete_commento").click(function(event){
            event.preventDefault();
            if (confirm("Are you sure to empty the comments for these leads?")) {
                var leads_ids=get_Selected_id();
                if (leads_ids!='') {
                    $('#delete_comments_ids').eq(0).val(leads_ids);
                    $('#delete_comments_form').submit();
                } else {
                    return confirm("No leads selected");
                }
            }
            return false;
        });
        
                    flatpickr("#flatpickr");
        
        $("#assign_button").click(function(event){
            event.preventDefault();
                var leads_ids=get_Selected_id();
                if (leads_ids!='') {
                    $('#assign_leads_ids').eq(0).val(leads_ids);
                    $('#assign_users').submit();
                } else {
                    return confirm("No leads selected");
                }
            return false;
        });
        $("#change_button").click(function(event){
            event.preventDefault();
            var leads_ids=get_Selected_id();
            if (leads_ids!='') {
                $('#change_leads_ids').eq(0).val(leads_ids);
                $('#change_status').submit();
            } else {
                return confirm("No leads selected");
            }
            return false;
        });*/

    });
</script>
<script>
  // Unix time value from server: seconds since 1970-01-01T00:00:00Z
  // Below is a number for 2014-07-02T06:48:24.000Z, set to actual server value
  var serverTime = 	Math.floor(new Date().getTime()/1000.0);
  
  var doClock = (function () {
  
    // Calc offset from server time
    // Javascript time value is milliseconds since above epoch
    var serverOffset = serverTime - (new Date() / 1000 | 0);
  
    // Helper
    function z(n){return (n<10?'0':'') + n}
  
    return function() {
  
      // Create a new Date object each time so
      // it doesn't matter if a second or more is skipped
      var now = new Date();
  
      // Adjust for server offset
      now.setSeconds(now.getSeconds() + serverOffset);
  
      // write clock to document, values are local, not UTC
      document.getElementById('clock').innerHTML = z(now.getHours())   + ':' +
                                                   z(now.getMinutes()) + ':' +
                                                   z(now.getSeconds());
      // Run again just after next full second
      setTimeout(doClock, 1020 - now.getMilliseconds());
    };    
  }());
  
  window.onload = doClock;
  
  </script>
{% endblock content %}