crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/',  include('users.urls', namespace="users")),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('categories/',  include('categories.urls', namespace="categories")),
    path('sources/',  include('sources.urls', namespace="sources")),
]

sources/urls.py
from django.urls import path
from .views import MixViewSource, SourceCreateView, SourceUpdateView, source_delete


app_name = 'sources'

urlpatterns =[
    path('', MixViewSource.as_view(), name='source-index'),
    path('<int:pk>/update/', SourceUpdateView.as_view(), name='source-update'),
    path('create/', SourceCreateView.as_view(), name='source-create'),
    path('<int:pk>/delete/', source_delete, name='source-delete'),
]

sources/models.py
from django.db import models

# Create your models here.

class Source (models.Model):
   
    source = models.CharField(unique=True, max_length=30)
    
    def __str__(self):
        return self.source

sources/forms.py
from django import forms
from django.forms import ModelForm
from .models import Source

class SourceModelForm(forms.ModelForm):
  class Meta:
    model = Source
    fields = (
        'source',
    )

sources/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic
from .forms import SourceModelForm
from .models import Source


class SourceCreateView(generic.CreateView):
    model = Source
    template_name = "sources/source_create.html"
    form_class = SourceModelForm

    def get_success_url(self):
       return reverse("sources:source-index")


class SourceUpdateView(generic.UpdateView):
   model = Source
   template_name = "sources/source_update.html"
   form_class = SourceModelForm
    
   def get_success_url(self):
     return reverse("sources:source-index")


class MixViewSource(generic.View):
    def get(self, request):
        allsources = Source.objects.order_by('id')
        form = SourceModelForm
        context = {
            'sources': allsources,
            'form': form
        }
        return  render(request, "sources/source_index.html", context)


def source_delete(request, pk):
    source = Source.objects.get(id=pk)
    source.delete()
    return redirect("/sources")

sources/templates/sources/source_create.html
{% extends "base.html" %}
{{form.media}}
{% block title %}
  create source
{% endblock title %}
{% block content %}
<style>
  .holder{
    background-color: #fff;
    border-radius: 10px;
  }
</style>
  <div class="holder">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Create a new source now.</h3>
          <div class="jumbotron">
          <form method="post" novalidate>
            {% csrf_token %}
            {{form}}
        </div>
      </div>
        <div class="card-footer text-muted text-center">
            <button type="submit" class="btn btn-success btn-block">Submit</button>
       </form>
       <h1><a href="/sources"><button class="btn btn-danger btn col-md-12"><span class="fa fa-undo" aria-hidden="true"></span> Back</button></a></h1>
       </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

sources/templates/sources/source_index.html
{%extends 'base.html'%}
{% load widget_tweaks %}
<title>
	{% block title %}
	  categories
	{% endblock title %}
  </title>
  <body>
{%block content%}
<div class="spoon">
		<div class="host">
			<h1>
				Sources Workspace.
			</h1>
			<h3>
				See the listed sources or create a new one by the form in the right.
			</h3>
		</div>
		<div class="peer">
			<h2>Create a new source.</h2>
			<form action="{% url 'sources:source-create' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					{% render_field form.source class="form-control" placeholder="Source" style="border-radius: 20px;" %}
				</div>
				<button type="submit" class="btn btn-dark col-12">Create</button>
			</form>
		</div>
</div>
<div class="content">
<table id="sources" class="table table-bordered nowrap table-sm" cellspacing="0" style="width:100%">
    {% csrf_token %}
	<thead class="thead-dark">
		<tr>
			<th class="text-center">#</th>
			<th class="text-center">Source</th>
			<th class="text-center">Action</th>
		</tr>
	</thead>
	<tbody>
		{% for source in sources %}
		<tr id="{{lead.id}}">
			<td class="text-center">{{source.id}}</td>
			<td class="text-center"><a href="{% url 'sources:source-update' source.pk %}">{{source}}</a></td>
			<td class="text-center">
				<a href="{% url 'sources:source-update' source.pk %}"><i class="fas fa-edit text-primary"></i></a>
				<a href="{% url 'sources:source-delete' source.pk %}" onclick="return confirm('Are you sure to delete this Source?');"><i class="fas fa-trash-alt text-danger"></i></a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if is_paginated %}
<nav aria-label="Page navigation example">
<ul class="pagination justify-content-center pagination-circle">
 {% if page_obj.has_previous %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-left text-dark"></i> Previous</a></li>
{% else %}
  <li class="page-item"><a><span class="page-link text-secondary">&laquo;</span></a></li>
{% endif %}
{% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="active page-item text-secondary"><span class="page-link">{{ i }}</span></li>
  {% else %}
  <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.next_page_number }}">Next <i class="fas fa-arrow-right text-dark"></i></a></li>
{% else %}
  <li class="page-item"><span class="page-link text-secondary">&raquo;</span></li>
{% endif %}
</ul>
</nav>
{% endif %}
<br><br>
<script>
    $(document).ready(function(){
        var table = $('#sources').DataTable({
            "paging":true,
            "aLengthMenu":[[10,25,50,100],[10,25,50,100]],
            "iDisplayLength":25,
            "searching":false,
            "responsive":true,
            "order": []
        });
	});
</script>
</div>
{%endblock content%}
</body>

sources/templates/sources/source_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{{form.media}}
{% block title %}
Update {{source}}
{% endblock title %}
{% block content %}
  <br><br><br>
  <div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Update {{source}}</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        </div>
        <div class="card-footer text-muted text-center">
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
       </form>
       <h1><a href="/sources"><button class="btn btn-danger btn col-md-12"><span class="fa fa-undo" aria-hidden="true"></span> Back</button></a></h1>
       </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}