categories/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import CategoryCreateView, CategoryUpdateView, MixViewCategory, category_delete


app_name = 'categories'

urlpatterns =[
    path('', login_required(MixViewCategory.as_view()), name='category-index'),
    path('<int:pk>/update/', login_required(CategoryUpdateView.as_view()), name='category-update'),
    path('create/', login_required(CategoryCreateView.as_view()), name='category-create'),
    path('<int:pk>/delete/', login_required(category_delete), name='category-delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/',  include('users.urls', namespace="users")),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('categories/',  include('categories.urls', namespace="categories")),
    path('sources/',  include('sources.urls', namespace="sources")),
]

categories/models.py
from django.db import models

# Create your models here.

class Category (models.Model):
   
    category = models.CharField(unique=True, max_length=30)
    
    def __str__(self):
        return self.category

categories/forms.py
from django import forms
from django.forms import ModelForm
from .models import Category

class CategoryModelForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = (
        'category',
    )

categories/views.py
from django.shortcuts import render, reverse, redirect
from django.views import generic
from .forms import CategoryModelForm
from .models import Category


class CategoryCreateView(generic.CreateView):
    model = Category
    template_name = "categories/category_create.html"
    form_class = CategoryModelForm

    def get_success_url(self):
       return reverse("categories:category-index")

class MixViewCategory(generic.View):
    def get(self, request):
        allcategories = Category.objects.order_by('id')
        form = CategoryModelForm
        context = {
            'categories': allcategories,
            'form': form
        }
        return  render(request, "categories/category_index.html", context)



class CategoryUpdateView(generic.UpdateView):
   model = Category
   template_name = "categories/category_update.html"
   form_class = CategoryModelForm
    
   def get_success_url(self):
     return reverse("categories:category-index")


def category_delete(request, pk):
    category = Category.objects.get(id=pk)
    category.delete()
    return redirect("/categories")

categories/templates/categories/category_create.html
{% extends "base.html" %}
{{form.media}}
{% block title %}
  create category
{% endblock title %}
{% block content %}
  <div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Create a new category now.</h3>
          <div class="jumbotron">
          <form method="post" novalidate>
            {% csrf_token %}
            {{form}}
        </div>
      </div>
        <div class="card-footer text-muted text-center">
            <button type="submit" class="btn btn-success btn-block">Submit</button>
       </form>
       <h1><a href="/categories"><button class="btn btn-danger btn col-md-12"><span class="fa fa-undo" aria-hidden="true"></span> Back</button></a></h1>
       </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

categories/templates/categories/category_index.html
{%extends 'base.html'%}
{% load widget_tweaks %}
<title>
	{% block title %}
	  categories
	{% endblock title %}
  </title>
  <body>
{%block content%}
<div class="spoon">
		<div class="host">
			<h1>
				Category Workspace.
			</h1>
			<h3>
				See the listed categories or create a new one by the form in the right.
			</h3>
		</div>
		<div class="peer">
			<h2>Create a new category.</h2>
			<form action="{% url 'categories:category-create' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					{% render_field form.category class="form-control" placeholder="Category" style="border-radius: 20px;" %}
				</div>
				<button type="submit" class="btn btn-dark col-12">Create</button>
			</form>
		</div>
</div>
<div class="content">
<table id="categories" class="table table-bordered nowrap table-sm" cellspacing="0" style="width:100%">
    {% csrf_token %}
	<thead class="thead-dark">
		<tr>
			<th class="text-center">#</th>
			<th class="text-center">Category</th>
			<th class="text-center">Action</th>
		</tr>
	</thead>
	<tbody>
		{% for category in categories %}
		<tr id="{{lead.id}}">
			<td class="text-center">{{category.id}}</td>
			<td class="text-center"><a href="{% url 'categories:category-update' category.pk %}">{{category}}</a></td>
			<td class="text-center">
				<a href="{% url 'categories:category-update' category.pk %}"><i class="fas fa-edit text-primary"></i></a>
				<a href="{% url 'categories:category-delete' category.pk %}" onclick="return confirm('Are you sure to delete this Category?');"><i class="fas fa-trash-alt text-danger"></i></a>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if is_paginated %}
<nav aria-label="Page navigation example">
<ul class="pagination justify-content-center pagination-circle">
 {% if page_obj.has_previous %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-arrow-left text-dark"></i> Previous</a></li>
{% else %}
  <li class="page-item"><a><span class="page-link text-secondary">&laquo;</span></a></li>
{% endif %}
{% for i in paginator.page_range %}
  {% if page_obj.number == i %}
  <li class="active page-item text-secondary"><span class="page-link">{{ i }}</span></li>
  {% else %}
  <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
  {% endif %}
{% endfor %}
{% if page_obj.has_next %}
  <li class="page-item"><a class="page-link text-secondary" href="?page={{ page_obj.next_page_number }}">Next <i class="fas fa-arrow-right text-dark"></i></a></li>
{% else %}
  <li class="page-item"><span class="page-link text-secondary">&raquo;</span></li>
{% endif %}
</ul>
</nav>
{% endif %}
<br><br>
<script>
    $(document).ready(function(){
        var table = $('#categories').DataTable({
            "paging":true,
            "aLengthMenu":[[10,25,50,100],[10,25,50,100]],
            "iDisplayLength":25,
            "searching":false,
            "responsive":true,
            "order": []
        });
	});
</script>
</div>
{%endblock content%}
</body>

categories/templates/categories/category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{{form.media}}
{% block title %}
update {{category}}
{% endblock title %}
{% block content %}
  <div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Update <b class="text-info">{{category}}</b></h3>
          <div class="jumbotron">
          <form method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
        </div>
        </div>
        <div class="card-footer text-muted text-center">
            <button type="submit" class="btn btn-success btn-block">Submit</button>
       </form>
       <h1><a href="/categories"><button class="btn btn-danger btn col-md-12"><span class="fa fa-undo" aria-hidden="true"></span> Back</button></a></h1>
       </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}